controllers:
    resource: '../src/Controller/'
    type: attribute

post_index:
    path: /post
    controller: App\Controller\PostController::index

post_new:
    path: /post/new
    controller: App\Controller\PostController::new

post_show:
    path: /post/{id}
    controller: App\Controller\PostController::show

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
